version: '3.2'

services:
  agent:
    image: portainer/agent:2.11.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    depends_on: [traefik]
    image: portainer/portainer-ce:2.11.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000" #tem que mudar essa porta aqui quando arrumar o target group e security groups
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.docker.network=traefik-public"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer_portainer.entrypoints=web"
      - "traefik.http.routers.portainer_portainer.rule=Host(`porta.localhost`)"
      - "traefik.http.services.portainer_portainer-service.loadbalancer.server.port=9000"
      - "traefik.tags"
  
  traefik:
    image: "traefik:v2.1"
    command:
         - --entrypoints.web.address=:80
         #- --entrypoints.websecure.address=:443
         - --providers.docker
         - --providers.docker.swarmMode=true
         - --providers.docker.network=traefik-public
         - --api
        # - --api.insecure=true
         - --log.level=INFO
         - --accesslog=true
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
       #DASHBOARD
        - "traefik.http.routers.traefik.rule=Host(`traefik.plataformarkade.com`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$tmtjEBIu$SqADg63v7k/0sOk6zlm8o0"
        - "traefik.http.services.traefik-traefik-service.loadbalancer.server.port=8080"
    networks:
      - traefik-public

networks:
  traefik-public:
     driver: overlay
     external: true
  agent_network:
    driver: overlay

volumes:
  portainer_data:
